"""add expires_at

Revision ID: b988e07fbbcf
Revises: d6805160acf8
Create Date: 2024-03-20 14:09:24.529984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b988e07fbbcf'
down_revision: Union[str, None] = 'd6805160acf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral', 'expires_at')
    # ### end Alembic commands ###
